# Configuration Générale de GensCore

# Configuration du Panel Web Administratif
web:
  # Activer ou désactiver le panel web
  enabled: false
  # Port sur lequel le panel sera accessible (ex: http://ip-du-serveur:8080)
  port: 8080

# Mot de passe pour accéder au Panel Web Admin
admin-password: "gens"

# Configuration Discord (Module JDA)
discord:
  # Token du Bot Discord (VOTRE_TOKEN_ICI pour désactiver le bot)
  bot_token: "VOTRE_TOKEN_ICI"

# Configuration BlueMap
bluemap:
  # L'URL où votre BlueMap est hébergée (utilisé par le panel web)
  url: "http://localhost:8100"

# Paramètres pour les Quêtes Journalières
quests:
  # Activer ou désactiver le module des quêtes
  enabled: true
  # Limite maximale de relance (reroll) de quête par joueur et par jour
  max_rerolls_per_day: 3

modules:
  tomb:
    enabled: true
    block_type: CHEST
    store_xp: true
    expiration_time_seconds: 3600
    expiration_action: UNLOCK
    default_access: OWNER_ONLY

# Temps d'attente (en secondes) avant une téléportation
teleport-cooldown: 3
