# Configuration Générale de GensCore

# Configuration du Panel Web Administratif
web:
  # Activer ou désactiver le panel web
  enabled: false
  # Port sur lequel le panel sera accessible (ex: http://ip-du-serveur:8080)
  port: 8080

# Mot de passe pour accéder au Panel Web Admin
admin-password: "gens"

# Configuration Discord (Module JDA)
discord:
  # Token du Bot Discord (VOTRE_TOKEN_ICI pour désactiver le bot)
  bot_token: "VOTRE_TOKEN_ICI"

# Configuration BlueMap
bluemap:
  # L'URL où votre BlueMap est hébergée (utilisé par le panel web)
  url: "http://localhost:8100"

# Paramètres pour les Quêtes Journalières
quests:
  # Activer ou désactiver le module des quêtes
  enabled: true
  # Limite maximale de relance (reroll) de quête par joueur et par jour
  max_rerolls_per_day: 3

modules:
  tomb:
    # Activer ou désactiver le module des tombes
    enabled: true
    # Type de bloc utilisé pour la tombe (ex: CHEST, BARREL, PLAYER_HEAD)
    block_type: CHEST
    # Sauvegarder l'expérience (XP) du joueur dans la tombe ?
    store_xp: true
    # Temps d'expiration de la tombe en secondes (ex: 3600 = 1 heure)
    expiration_time_seconds: 3600
    # Action à effectuer à l'expiration (UNLOCK, DROP, DESTROY)
    # UNLOCK: Tout le monde peut l'ouvrir
    # DROP: Lâche les items au sol
    # DESTROY: Supprime la tombe et les items
    expiration_action: UNLOCK
    # Accès par défaut avant expiration (OWNER_ONLY ou EVERYONE)
    default_access: OWNER_ONLY

# Temps d'attente (en secondes) avant une téléportation
teleport-cooldown: 3
