// Generated Minecraft Textures Dictionary for 100% accurate rendering
export const MINECRAFT_TEXTURE_MAP: Record<string, string> = {
  "acacia_log": "block/acacia_log_top",
  "acacia_planks": "block/acacia_planks",
  "acacia_sapling": "block/acacia_sapling",
  "acacia_wood": "block/acacia_log",
  "amethyst_block": "block/amethyst_block",
  "amethyst_shard": "item/amethyst_shard",
  "ancient_debris": "block/ancient_debris_top",
  "andesite": "block/andesite",
  "anvil": "block/anvil_top",
  "apple": "item/apple",
  "armadillo_scute": "item/armadillo_scute",
  "baked_potato": "item/baked_potato",
  "bamboo": "item/bamboo",
  "bamboo_block": "block/bamboo_block_top",
  "bamboo_planks": "block/bamboo_planks",
  "barrel": "block/barrel_bottom",
  "basalt": "block/basalt_top",
  "beacon": "block/glass",
  "beef": "item/beef",
  "beetroot": "item/beetroot",
  "beetroot_seeds": "item/beetroot_seeds",
  "beetroot_soup": "item/beetroot_soup",
  "birch_log": "block/birch_log_top",
  "birch_planks": "block/birch_planks",
  "birch_sapling": "block/birch_sapling",
  "birch_wood": "block/birch_log",
  "blackstone": "block/blackstone_top",
  "black_concrete": "block/black_concrete",
  "black_wool": "block/black_wool",
  "blast_furnace": "block/blast_furnace_front",
  "blaze_powder": "item/blaze_powder",
  "blaze_rod": "item/blaze_rod",
  "bone": "item/bone",
  "bone_block": "block/bone_block_top",
  "bone_meal": "item/bone_meal",
  "bookshelf": "block/oak_planks",
  "bread": "item/bread",
  "breeze_rod": "item/breeze_rod",
  "brewing_stand": "item/brewing_stand",
  "bricks": "block/bricks",
  "brown_mushroom": "block/brown_mushroom",
  "bucket": "item/bucket",
  "cactus": "block/cactus_side",
  "cake": "item/cake",
  "campfire": "item/campfire",
  "carrot": "item/carrot",
  "cartography_table": "block/dark_oak_planks",
  "carved_pumpkin": "block/carved_pumpkin",
  "cauldron": "item/cauldron",
  "charcoal": "item/charcoal",
  "cherry_log": "block/cherry_log_top",
  "cherry_planks": "block/cherry_planks",
  "cherry_sapling": "block/cherry_sapling",
  "cherry_wood": "block/cherry_log",
  "chest": "item/chest_minecart",
  "chicken": "item/chicken",
  "chipped_anvil": "block/chipped_anvil_top",
  "chiseled_bookshelf": "block/chiseled_bookshelf_top",
  "chiseled_deepslate": "block/chiseled_deepslate",
  "chiseled_stone_bricks": "block/chiseled_stone_bricks",
  "chiseled_tuff_bricks": "block/chiseled_tuff_bricks_top",
  "chorus_fruit": "item/chorus_fruit",
  "clay": "block/clay",
  "clock": "item/clock_00",
  "coal": "item/coal",
  "coal_block": "block/coal_block",
  "cobbled_deepslate": "block/cobbled_deepslate",
  "cobblestone": "block/cobblestone",
  "cobweb": "block/cobweb",
  "cocoa_beans": "item/cocoa_beans",
  "cod": "item/cod",
  "comparator": "item/comparator",
  "compass": "item/compass_16",
  "cooked_beef": "item/cooked_beef",
  "cooked_chicken": "item/cooked_chicken",
  "cooked_cod": "item/cooked_cod",
  "cooked_mutton": "item/cooked_mutton",
  "cooked_porkchop": "item/cooked_porkchop",
  "cooked_rabbit": "item/cooked_rabbit",
  "cooked_salmon": "item/cooked_salmon",
  "cookie": "item/cookie",
  "copper_block": "block/copper_block",
  "copper_ingot": "item/copper_ingot",
  "cracked_stone_bricks": "block/cracked_stone_bricks",
  "crafting_table": "block/oak_planks",
  "crimson_fungus": "block/crimson_fungus",
  "crimson_planks": "block/crimson_planks",
  "crimson_stem": "block/crimson_stem_top",
  "crying_obsidian": "block/crying_obsidian",
  "damaged_anvil": "block/damaged_anvil_top",
  "dark_oak_log": "block/dark_oak_log_top",
  "dark_oak_planks": "block/dark_oak_planks",
  "dark_oak_sapling": "block/dark_oak_sapling",
  "dark_oak_wood": "block/dark_oak_log",
  "dark_prismarine": "block/dark_prismarine",
  "deepslate": "block/deepslate_top",
  "deepslate_bricks": "block/deepslate_bricks",
  "deepslate_tiles": "block/deepslate_tiles",
  "diamond": "item/diamond",
  "diamond_block": "block/diamond_block",
  "diorite": "block/diorite",
  "dispenser": "block/dispenser_front",
  "dragon_breath": "item/dragon_breath",
  "dried_kelp": "item/dried_kelp",
  "dried_kelp_block": "block/dried_kelp_side",
  "dropper": "block/dropper_front",
  "egg": "item/egg",
  "elytra": "item/elytra",
  "emerald": "item/emerald",
  "emerald_block": "block/emerald_block",
  "enchanted_golden_apple": "item/golden_apple",
  "enchanting_table": "block/enchanting_table_bottom",
  "ender_chest": "block/obsidian",
  "ender_eye": "item/ender_eye",
  "ender_pearl": "item/ender_pearl",
  "end_stone": "block/end_stone",
  "end_stone_bricks": "block/end_stone_bricks",
  "experience_bottle": "item/experience_bottle",
  "feather": "item/feather",
  "fermented_spider_eye": "item/fermented_spider_eye",
  "furnace": "block/furnace_front",
  "ghast_tear": "item/ghast_tear",
  "glass": "block/glass",
  "glass_bottle": "item/glass_bottle",
  "glistering_melon_slice": "item/glistering_melon_slice",
  "glowstone": "block/glowstone",
  "glowstone_dust": "item/glowstone_dust",
  "glow_berries": "item/glow_berries",
  "glow_ink_sac": "item/glow_ink_sac",
  "golden_apple": "item/golden_apple",
  "golden_carrot": "item/golden_carrot",
  "gold_block": "block/gold_block",
  "gold_ingot": "item/gold_ingot",
  "gold_nugget": "item/gold_nugget",
  "granite": "block/granite",
  "gravel": "block/gravel",
  "gray_concrete": "block/gray_concrete",
  "grindstone": "block/grindstone_pivot",
  "gunpowder": "item/gunpowder",
  "hay_block": "block/hay_block_top",
  "heavy_core": "block/heavy_core",
  "honeycomb": "item/honeycomb",
  "honeycomb_block": "block/honeycomb_block",
  "honey_block": "block/honey_block_top",
  "honey_bottle": "item/honey_bottle",
  "hopper": "item/hopper",
  "ink_sac": "item/ink_sac",
  "iron_block": "block/iron_block",
  "iron_ingot": "item/iron_ingot",
  "iron_nugget": "item/iron_nugget",
  "jack_o_lantern": "block/jack_o_lantern",
  "jungle_log": "block/jungle_log_top",
  "jungle_planks": "block/jungle_planks",
  "jungle_sapling": "block/jungle_sapling",
  "jungle_wood": "block/jungle_log",
  "kelp": "item/kelp",
  "lantern": "item/lantern",
  "lapis_block": "block/lapis_block",
  "lapis_lazuli": "item/lapis_lazuli",
  "lava_bucket": "item/lava_bucket",
  "lead": "item/lead",
  "leather": "item/leather",
  "lightning_rod": "block/lightning_rod",
  "lingering_potion": "item/potion_overlay",
  "loom": "block/loom_bottom",
  "magma_block": "block/magma",
  "magma_cream": "item/magma_cream",
  "mangrove_log": "block/mangrove_log_top",
  "mangrove_planks": "block/mangrove_planks",
  "mangrove_propagule": "item/mangrove_propagule",
  "mangrove_wood": "block/mangrove_log",
  "melon": "block/melon_top",
  "melon_seeds": "item/melon_seeds",
  "melon_slice": "item/melon_slice",
  "milk_bucket": "item/milk_bucket",
  "mossy_cobblestone": "block/mossy_cobblestone",
  "mossy_stone_bricks": "block/mossy_stone_bricks",
  "mud": "block/mud",
  "mud_bricks": "block/mud_bricks",
  "mushroom_stew": "item/mushroom_stew",
  "mutton": "item/mutton",
  "name_tag": "item/name_tag",
  "netherite_block": "block/netherite_block",
  "netherite_ingot": "item/netherite_ingot",
  "netherite_scrap": "item/netherite_scrap",
  "netherrack": "block/netherrack",
  "nether_bricks": "block/nether_bricks",
  "nether_star": "item/nether_star",
  "nether_wart": "item/nether_wart",
  "oak_log": "block/oak_log_top",
  "oak_planks": "block/oak_planks",
  "oak_sapling": "block/oak_sapling",
  "oak_wood": "block/oak_log",
  "observer": "block/observer_back",
  "obsidian": "block/obsidian",
  "ominous_bottle": "item/ominous_bottle",
  "packed_mud": "block/packed_mud",
  "pale_oak_log": "block/pale_oak_log",
  "pale_oak_planks": "block/pale_oak_planks",
  "pale_oak_sapling": "item/pale_oak_sapling",
  "pale_oak_wood": "block/pale_oak_wood",
  "phantom_membrane": "item/phantom_membrane",
  "piston": "block/piston_bottom",
  "poisonous_potato": "item/poisonous_potato",
  "polished_andesite": "block/polished_andesite",
  "polished_basalt": "block/polished_basalt_top",
  "polished_blackstone": "block/polished_blackstone",
  "polished_blackstone_bricks": "block/polished_blackstone_bricks",
  "polished_deepslate": "block/polished_deepslate",
  "polished_diorite": "block/polished_diorite",
  "polished_granite": "block/polished_granite",
  "polished_tuff": "block/polished_tuff",
  "popped_chorus_fruit": "item/popped_chorus_fruit",
  "porkchop": "item/porkchop",
  "potato": "item/potato",
  "potion": "item/potion_overlay",
  "prismarine": "block/prismarine",
  "prismarine_bricks": "block/prismarine_bricks",
  "prismarine_crystals": "item/prismarine_crystals",
  "prismarine_shard": "item/prismarine_shard",
  "pufferfish": "item/pufferfish",
  "pumpkin": "block/pumpkin_top",
  "pumpkin_pie": "item/pumpkin_pie",
  "pumpkin_seeds": "item/pumpkin_seeds",
  "purpur_block": "block/purpur_block",
  "purpur_pillar": "block/purpur_pillar_top",
  "quartz": "item/quartz",
  "quartz_block": "block/quartz_block_top",
  "rabbit": "item/rabbit",
  "rabbit_foot": "item/rabbit_foot",
  "rabbit_hide": "item/rabbit_hide",
  "rabbit_stew": "item/rabbit_stew",
  "raw_copper": "item/raw_copper",
  "raw_copper_block": "block/raw_copper_block",
  "raw_gold": "item/raw_gold",
  "raw_gold_block": "block/raw_gold_block",
  "raw_iron": "item/raw_iron",
  "raw_iron_block": "block/raw_iron_block",
  "recovery_compass": "item/recovery_compass_16",
  "redstone": "item/redstone",
  "redstone_block": "block/redstone_block",
  "redstone_torch": "block/redstone_torch",
  "red_mushroom": "block/red_mushroom",
  "red_nether_bricks": "block/red_nether_bricks",
  "red_sand": "block/red_sand",
  "red_sandstone": "block/red_sandstone_bottom",
  "repeater": "item/repeater",
  "rotten_flesh": "item/rotten_flesh",
  "saddle": "item/saddle",
  "salmon": "item/salmon",
  "sand": "block/sand",
  "sandstone": "block/sandstone_bottom",
  "sea_lantern": "block/sea_lantern",
  "sea_pickle": "item/sea_pickle",
  "shroomlight": "block/shroomlight",
  "shulker_box": "block/shulker_box",
  "shulker_shell": "item/shulker_shell",
  "slime_ball": "item/slime_ball",
  "slime_block": "block/slime_block",
  "smithing_table": "block/smithing_table_bottom",
  "smoker": "block/smoker_bottom",
  "smooth_basalt": "block/smooth_basalt",
  "smooth_red_sandstone": "block/red_sandstone_top",
  "smooth_sandstone": "block/sandstone_top",
  "smooth_stone": "block/smooth_stone",
  "soul_campfire": "item/soul_campfire",
  "soul_lantern": "item/soul_lantern",
  "soul_torch": "block/soul_torch",
  "spider_eye": "item/spider_eye",
  "splash_potion": "item/potion_overlay",
  "sponge": "block/sponge",
  "spruce_log": "block/spruce_log_top",
  "spruce_planks": "block/spruce_planks",
  "spruce_sapling": "block/spruce_sapling",
  "spruce_wood": "block/spruce_log",
  "spyglass": "item/spyglass",
  "sticky_piston": "block/piston_bottom",
  "stone": "block/stone",
  "stonecutter": "block/stonecutter_bottom",
  "stone_bricks": "block/stone_bricks",
  "string": "item/string",
  "stripped_acacia_log": "block/stripped_acacia_log_top",
  "stripped_bamboo_block": "block/stripped_bamboo_block_top",
  "stripped_birch_log": "block/stripped_birch_log_top",
  "stripped_cherry_log": "block/stripped_cherry_log_top",
  "stripped_crimson_stem": "block/stripped_crimson_stem_top",
  "stripped_dark_oak_log": "block/stripped_dark_oak_log_top",
  "stripped_jungle_log": "block/stripped_jungle_log_top",
  "stripped_mangrove_log": "block/stripped_mangrove_log_top",
  "stripped_oak_log": "block/stripped_oak_log_top",
  "stripped_pale_oak_log": "block/stripped_pale_oak_log",
  "stripped_spruce_log": "block/stripped_spruce_log_top",
  "stripped_warped_stem": "block/stripped_warped_stem_top",
  "sugar": "item/sugar",
  "sugar_cane": "item/sugar_cane",
  "sweet_berries": "item/sweet_berries",
  "target": "block/target_top",
  "terracotta": "block/terracotta",
  "tinted_glass": "block/tinted_glass",
  "tipped_arrow": "item/tipped_arrow_head",
  "tnt": "block/tnt_bottom",
  "torch": "block/torch",
  "totem_of_undying": "item/totem_of_undying",
  "trapped_chest": "item/chest_minecart",
  "trident": "item/trident",
  "spear": "item/iron_spear",
  "lance": "item/iron_spear",
  "wooden_spear": "item/wooden_spear",
  "stone_spear": "item/stone_spear",
  "copper_spear": "item/copper_spear",
  "iron_spear": "item/iron_spear",
  "golden_spear": "item/golden_spear",
  "diamond_spear": "item/diamond_spear",
  "netherite_spear": "item/netherite_spear",
  "lance_en_bois": "item/wooden_spear",
  "lance_en_pierre": "item/stone_spear",
  "lance_en_cuivre": "item/copper_spear",
  "lance_en_fer": "item/iron_spear",
  "lance_en_or": "item/golden_spear",
  "lance_en_diamant": "item/diamond_spear",
  "lance_en_netherite": "item/netherite_spear",
  "mace": "item/mace",
  "pointed_dripstone": "item/pointed_dripstone",
  "tropical_fish": "item/tropical_fish",
  "tuff": "block/tuff",
  "tuff_bricks": "block/tuff_bricks",
  "turtle_scute": "item/turtle_scute",
  "warped_fungus": "block/warped_fungus",
  "warped_planks": "block/warped_planks",
  "warped_stem": "block/warped_stem_top",
  "water_bucket": "item/water_bucket",
  "wheat": "item/wheat",
  "wheat_seeds": "item/wheat_seeds",
  "white_concrete": "block/white_concrete",
  "white_terracotta": "block/white_terracotta",
  "white_wool": "block/white_wool",
  "wind_charge": "item/wind_charge"
};

const MC_ASSETS_VERSION = '26.3';

export function getMinecraftItemUrl(material: string): string {
  if (!material) return '';
  const clean = material.toLowerCase().trim();
  
  if (MINECRAFT_TEXTURE_MAP[clean]) {
    return `https://assets.mcasset.cloud/${MC_ASSETS_VERSION}/assets/minecraft/textures/${MINECRAFT_TEXTURE_MAP[clean]}.png`;
  }

  // Fallback direct pour toute lance / spear générique
  if (clean === 'spear' || clean === 'lance') {
    return `https://assets.mcasset.cloud/${MC_ASSETS_VERSION}/assets/minecraft/textures/item/iron_spear.png`;
  }
  
  // Dynamic fallback for any other material
  if (clean.endsWith('_block') || clean.endsWith('_log') || clean.endsWith('_planks') || clean.includes('stone') || clean.includes('brick')) {
    return `https://assets.mcasset.cloud/${MC_ASSETS_VERSION}/assets/minecraft/textures/block/${clean}.png`;
  }
  return `https://assets.mcasset.cloud/${MC_ASSETS_VERSION}/assets/minecraft/textures/item/${clean}.png`;
}

export function handleMinecraftImageError(e: any) {
  const target = e.currentTarget;
  if (!target || target._hasRetriedTwice) {
    if (target) target.style.opacity = '0.3';
    return;
  }
  const current = target.src || '';
  if (!target._hasRetried) {
    target._hasRetried = true;
    if (current.includes('/item/')) {
      target.src = current.replace('/item/', '/block/');
    } else if (current.includes('/block/')) {
      target.src = current.replace('/block/', '/item/');
    }
  } else {
    target._hasRetriedTwice = true;
    if (current.includes('spear') || current.includes('lance')) {
      target.src = `https://assets.mcasset.cloud/${MC_ASSETS_VERSION}/assets/minecraft/textures/item/iron_spear.png`;
    }
  }
}

